name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version:'
        required: true
        type: choice
        options: 
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: Bump package version
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags origin

      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get next version
        run: |
          current_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          major=$(echo $current_tag | cut -dv -f2 | cut -d. -f1)
          minor=$(echo $current_tag | cut -dv -f2 | cut -d. -f2)
          patch=$(echo $current_tag | cut -dv -f2 | cut -d. -f3)
          case ${{ github.event.inputs.version }} in
            major)
              next_major=$((major + 1))
              next_version="${next_major}.0.0"
              ;;
            minor)
              next_minor=$((minor + 1))
              next_version="${major}.${next_minor}.0"
              ;;
            patch)
              next_patch=$((patch + 1))
              next_version="${major}.${minor}.${next_patch}"
              ;;
            *)
              echo "Invalid bump type: ${{ github.event.inputs.version }}"
              exit 1
              ;;
          esac
          echo "Next version is ${next_version}"
          echo "NEXT_VERSION=${next_version}" >> $GITHUB_ENV
          
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Bump npm package version 
        run: |
          cd npm
          npm version "${{ env.NEXT_VERSION }}" --no-git-tag-version

      - name: Create a new PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Bumping package to v${{ env.NEXT_VERSION }}
          branch: releases/v${{ env.NEXT_VERSION }}
          delete-branch: true
          title: 'Bumping package to v${{ env.NEXT_VERSION }}'
          body: |
            This PR bumps the version of the package to v${{ env.NEXT_VERSION }} (${{ github.event.inputs.version }}). 
            
            *Triggered by @${{ github.actor }}*
          reviewers: |
            alexnguyenn
            gwwatkin
          labels: releases
